eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

server:
  port: 8090

spring:
  application:
    name: students
  datasource:
    url: jdbc:sqlserver://localhost:1111;databaseName=students;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
